import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
       <Header/>
        <main className="flex-1 pt-20 md:pt-24 lg:pt-28">{children}</main>
        {/* {children} */}
        <Footer/>
      </body>
    </html>
  );
}

// import "./globals.css";
// import { Poppins } from "next/font/google";
// import Header from "./Components/Header";
// import Footer from "./Components/Footer";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
// });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.className} min-h-screen flex flex-col`}>
        
//         {/* FIXED HEADER — NEVER HIDES */}
//         <header className="fixed top-0 left-0 w-full z-50">
//           <Header />
//         </header>

//         {/* MAIN CONTENT — pushed below header */}
//         <main className="flex-1 pt-[90px]">
//           {children}
//         </main>

//         {/* FOOTER — normal flow */}
//         <Footer />

//       </body>
//     </html>
//   );
// }